name: Rust

on:
  workflow_dispatch:
    
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@master
      with:
        args: cd rust && cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
